export default{
    'label_bienvenido':'Accueillir',
    'inicia_sesion' : 'Commencer la session',
    'menu': 'Menu',
    'categorias' : 'Catégories',
    'Buscar productos' : 'Recherche de produits',
    'para mascotas' : 'pour les animaux de compagnie',
    'lo tenemos todo' : 'nous avons tout',
    'descubre' : 'découvrir',
    'lo mas nuevo' : 'le + nouveau',
    'conoce nuestras' : 'Découvrez nos ',
    'nuevas categorias' : 'nouvelles catégories',
    'aprovecha las' : 'Vous profitez des',
    'promociones' : 'promotions',
    'tus categorias favoritas' : 'Vos catégories préférées',
    'en marcas' :'Dans les marques',
    'emprendedores y pymes' : 'Entrepreneurs et pymes',

    'retiro en tienda' : 'Ramasser en Magasin',
    'mas de 30 tiendas a lo' : 'Plus de 30 magasins à',
    'largo del peru' : 'travers le Pérou',
    'atencion al cliente' : 'Attention au client',
    'extragarantia' : 'Garantie Supplémentaire',
    'prolonga la garantia' :'Prolonger la garantie',
    'de tus productos' : 'de vos produits',
    'devolucion' : 'Revenir',
    'cambios y' : 'Retours et',
    'Devoluciones' : 'Échanges',
    'servicio al cliente' : 'Service Clients',
    'como comprar en ripley' : '¿Comment acheter sur Ripley.com?',
    'guias de compra' : 'Guides d achat',
    'terminos y condiciones' : 'Termes et conditions',
    'cambios y devoluciones' : 'Retours et Échanges',
    'bases legales' : 'Bases Légales',
    'seguridad y privacidad' : 'Sécurité et confidentialité',
    'seguimiento de despacho' : 'Suivi d expédition',
    'politica de privacidad de datos' : 'Politique de confidentialité des données',
    'sobre ripley' : 'À propos de Ripley',
    'portal de personas': 'Portail des personnes',
    'quienes somos' : '¿Qui sommes nous?',
    'nuestras tiendas' : 'Nos boutiques',
    'trabaja con nosotros' : 'Travaille avec nous',
    'comprobante electronico' : 'Reçu électronique',
    'reporte de sostenibilidad' : 'Rapport de durabilité',
    'banco ripley' : 'Banque ripley',
    'tarjeta ripley': 'carte Ripley',
    'efectivo express': 'Espèces Expres',
    'ripleypuntos': 'RipleyPoints',
    'seguros ripley': 'Assurance Ripley',
    'extra garantia': 'Garantie supplémentaire',
    'cyber wow': 'Cyber Wow',
    'cyber day chile': 'Cyber Day chile',
    'ripley chile': 'Ripley Chile',
    'suscribete' : 'S\'abonner',
    'ingresa_correo' : 'Entrer votre Email',
    'acepto los terminos y condiciones': 'J\'accepte les termes et conditions',
    'medios de Pago': 'Méthodes de payement',
    'siguenos' : 'Suivez-nous',
    'parrafo1' : 'Pour votre sécurité, pensez à toujours vérifier dans votre navigateur que le site que vous visitez est la version officielle. L\'adresse https://simple.ripley.com.pe est la seule sur le site officiel de Ripley.',
    'parrafo2' : 'Prix ​​uniquement disponibles sur www.ripley.com.pe et Fonocompras. Les prix publiés sur Internet incluent une remise supplémentaire. Les prix peuvent changer sans avertissement. Produits sous réserve de disponibilité des stocks.' +
        'Consommation familiale uniquement. Stock minimum 1 unité par produit. Les offres sont régies selon les termes et conditions. L\'expédition du produit sera effectuée une fois l\'achat confirmé.'
}