export default{
    'label_bienvenido':'Welcome',
    'inicia_sesion' : 'Login',
    'menu': 'Categories',
    'categorias': 'Menu',
    'Buscar productos' : 'Search Products',
    'para mascotas' : 'For pets',
    'lo tenemos todo' : 'we have it all',
    'descubre': 'discover',
    'lo mas nuevo' : 'the + new',
    'conoce nuestras' :'meet our',
    'nuevas categorias' : 'new categories',
    'aprovecha las' : 'Take advantage of the',
    'promociones' : 'promotions',
    'tus categorias favoritas' : 'Your favorite categories',
    'en marcas' :'In brands',
    'emprendedores y pymes' : 'Entrepreneurs and pymes',

    'retiro en tienda' : 'Withdrawal in Store',
    'mas de 30 tiendas a lo' : 'More than 30 stores ',
    'largo del peru' : 'throughout Peru',
    'atencion al cliente' : 'Customer Support',
    'extragarantia' : 'Extra guarantee',
    'prolonga la garantia' : 'Extend the Warranty',
    'de tus productos' : 'of your products',
    'devolucion' : 'Return',
    'cambios y' : 'Returns &',
    'Devoluciones' : 'Exchanges',
    'servicio al cliente' : 'Customer service',
    'como comprar en ripley' : 'How to shop at Ripley.com?',
    'guias de compra' : 'Buying Guides',
    'terminos y condiciones' : 'Terms and Conditions',
    'cambios y devoluciones' : 'Returns & Exchanges',
    'bases legales' : 'Legal Bases',
    'seguridad y privacidad' : 'Security and Privacy',
    'seguimiento de despacho' : 'Dispatch Tracking',
    'politica de privacidad de datos' : 'Data Privacy Policy',
    'sobre ripley' : 'About Ripley',
    'portal de personas': 'People Portal',
    'quienes somos' : 'About us?',
    'nuestras tiendas' : 'Nuestras Tiendas',
    'trabaja con nosotros' : 'Our shops',
    'comprobante electronico' : 'Electronic receipt',
    'reporte de sostenibilidad' : 'Sustainability Report',
    'banco ripley' : 'Ripley Bank',
    'tarjeta ripley': 'Ripley Card',
    'efectivo express': 'Efectivo Express',
    'ripleypuntos': 'Express Cash',
    'seguros ripley': 'Ripley Insurance',
    'extra garantia': 'Extra Guarantee',
    'cyber wow': 'Cyber Wow',
    'cyber day chile': 'Cyber Day chile',
    'ripley chile': 'Ripley Chile',
    'suscribete' : 'Subscribe',
    'ingresa tu correo' : 'Enter your email',
    'acepto los terminos y condiciones': 'I accept the terms and conditions',
    'medios de Pago': 'Payment methods',
    'siguenos' : 'Follow us',
    'parrafo1' : 'For your safety, remember to always check in your browser that the site you visit is the official version.' +
                 'The address https://simple.ripley.com.pe is the only one on the official Ripley site.',
    'parrafo2' : 'Prices only available at www.ripley.com.pe and Fonocompras. Internet published prices include additional discount. Prices subject to change without notice. Products subject to stock availability.' +
        'Family consumption only. Minimum stock 1 unit per product. Offers are governed according to the terms and conditions. Dispatch of the product will be made once the purchase is confirmed.'
}