export default{
    'label_bienvenido': 'Bienvenid@',
    'inicia_sesion' : 'Iniciar Sesión',
    'menu': 'Menú de',
    'categorias' : 'Categorias',
    'Buscar productos' : 'Buscar productos',
    'para mascotas' : 'para mascotas',
    'lo tenemos todo' : 'lo tenemos todo',
    'descubre' : 'descubre',
    'lo mas nuevo' : 'lo + nuevo',
    'conoce nuestras' : 'conoce nuestras',
    'nuevas categorias' : 'nuevas categorías',
    'aprovecha las' : 'Aprovechas las',
    'promociones' : 'promociones',
    'tus categorias favoritas' : 'Tus categorias favoritas',
    'en marcas' :'En marcas',
    'emprendedores y pymes' : 'Emprendedores y pymes',

    'retiro en tienda' : 'Retiro en Tienda',
    'mas de 30 tiendas a lo' : 'Más de 30 tiendas a lo',
    'largo del peru' : 'largo del Perú',
    'atencion al cliente' : 'Atención al cliente',
    'extragarantia' : 'Extragarantía',
    'prolonga la garantia' : 'Prolonga la Garantía',
    'de tus productos' : 'de tus productos',
    'devolucion' : 'Devolución',
    'cambios y' : 'Cambios y',
    'Devoluciones' : 'devoluciones',
    'servicio al cliente' : 'Servicio al Cliente',
    'como comprar en ripley' : '¿Cómo comprar en Ripley.com?',
    'guias de compra' : 'Guías de Compra',
    'terminos y condiciones' : 'Términos y condiciones',
    'cambios y devoluciones' : 'Cambios y Devoluciones',
    'bases legales' : 'Bases Legales',
    'seguridad y privacidad' : 'Seguridad y Privacidad',
    'seguimiento de despacho' : 'Seguimiento de Despacho',
    'politica de privacidad de datos' : 'Política de privacidad de datos',
    'sobre ripley' : 'Sobre Ripley',
    'portal de personas': 'Portal de Personas',
    'quienes somos' : '¿Quiénes Somos?',
    'nuestras tiendas' : 'Nuestras Tiendas',
    'trabaja con nosotros' : 'Trabaja con Nosotros',
    'comprobante electronico' : 'Comprobante Electrónico',
    'reporte de sostenibilidad' : ' Reporte de Sostenibilidad',
    'banco ripley' : 'Banco Ripley',
    'tarjeta ripley': 'Tarjeta Ripley',
    'efectivo express': 'Efectivo Express',
    'ripleypuntos': 'RipleyPuntos',
    'seguros ripley': 'Seguros Ripley',
    'extra garantia': 'Extra Garantía',
    'cyber wow': 'Cyber Wow',
    'cyber day chile': 'Cyber Day chile',
    'ripley chile': 'Ripley Chile',
    'suscribete' : 'Suscríbete',
    'ingresa_correo' : 'Ingresa tu Correo',
    'acepto los terminos y condiciones': 'Acepto los Términos y condiciones',
    'medios de Pago': 'Medios de Pago',
    'siguenos' : 'Síguenos',
    'parrafo1' : 'Por tu seguridad, recuerda revisar siempre en tu navegador que el sitio que visitas sea la versión oficial.' +
                 'La dirección https://simple.ripley.com.pe es la única del sitio oficial de Ripley.',
    'parrafo2' : 'Precios solo disponibles en www.ripley.com.pe y Fonocompras. Precios Internet publicados incluyen descuento adicional. Precios sujetos a variaciones sin previo aviso. Productos sujetos a disponibilidad de stock.' +
        'Solo consumo familiar. Stock mínimo 1 unidad por producto. Ofertas se rigen de acuerdo a los términos y condiciones. Despacho de producto se realizará una vez confirmada la compra.'

}